<!--
	The default theme contents use theme inheritance.

	Application themes can extend an existing global theme using the
	extends attribute.  Existing themes include the following options:

	1. webstandard 2. oneui 3. notes
-->
<theme extends="Bootstrap3_flat" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="platform:/plugin/com.ibm.designer.domino.stylekits/schema/stylekit.xsd" >

</theme>
